# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M & D | Modern Business Consulting
email: info@getmikeanddan.com
description: > # this means to ignore newlines until "baseurl:"
  Mike and Dan is all about helping you fullfil your website needs. From fast fixes to full features,
  we are confident in our ability to be a temporary dev guy that integrates with your existing company.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://getmikeanddan.com" # the base hostname & protocol for your site
twitter_username: getmikeanddan
github_username:  mikeanddan
source:      .
destination: ./_site

# Build settings
markdown: kramdown
prod_mailbox: o80sm4ex@robot.zapier.com
local_mailbox: info@getmikeanddan.com
